// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: common/chat.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Represents chat member
struct ChatMember {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// User id
  var id: String = String()

  /// Determines is the member is currently authorized user
  var isCaller: Bool = false

  var type: UserTypeEnum = .userTypeUnknown

  /// admin of the chat, can be assigned by owner or other
  /// admin, owner user gets admin access as well
  var isAdmin: Bool = false

  /// creator of the chat, can't be assigned
  var isOwner: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// ChatSettings represents user specific configurations for the chat
struct ChatSettings {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Indicator that user from p2p chat can be accepted
  /// as contact. Can be "true" only for p2p chats
  var addContact: Bool = false

  /// indicates is it possible to call participant
  /// in case "callDisabledForNonContactUser" set to true
  /// then call will not be allowed in case receiver is not
  /// added sender to contacts
  var callAllowed: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct SupportChatSettings {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var status: SupportChatStatusEnum = .supportChatStatusClosed

  var assignedSupportManager: String = String()

  /// Format: UnixMicro
  var postponedTime: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Chat {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var chatType: ChatTypeEnum = .peerToPeer

  var chatID: String = String()

  var title: String = String()

  var unread: Int64 = 0

  var members: [ChatMember] = []

  var messageSeqNumber: UInt64 = 0

  var settings: ChatSettings {
    get {return _settings ?? ChatSettings()}
    set {_settings = newValue}
  }
  /// Returns true if `settings` has been explicitly set.
  var hasSettings: Bool {return self._settings != nil}
  /// Clears the value of `settings`. Subsequent reads from it will return its default value.
  mutating func clearSettings() {self._settings = nil}

  var supportSettings: SupportChatSettings {
    get {return _supportSettings ?? SupportChatSettings()}
    set {_supportSettings = newValue}
  }
  /// Returns true if `supportSettings` has been explicitly set.
  var hasSupportSettings: Bool {return self._supportSettings != nil}
  /// Clears the value of `supportSettings`. Subsequent reads from it will return its default value.
  mutating func clearSupportSettings() {self._supportSettings = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _settings: ChatSettings? = nil
  fileprivate var _supportSettings: SupportChatSettings? = nil
}

struct PeerUser {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var userID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct PeerChat {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var chatID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Peer {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var ofPeer: Peer.OneOf_OfPeer? = nil

  var user: PeerUser {
    get {
      if case .user(let v)? = ofPeer {return v}
      return PeerUser()
    }
    set {ofPeer = .user(newValue)}
  }

  var chat: PeerChat {
    get {
      if case .chat(let v)? = ofPeer {return v}
      return PeerChat()
    }
    set {ofPeer = .chat(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_OfPeer: Equatable {
    case user(PeerUser)
    case chat(PeerChat)

  #if !swift(>=4.1)
    static func ==(lhs: Peer.OneOf_OfPeer, rhs: Peer.OneOf_OfPeer) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.user, .user): return {
        guard case .user(let l) = lhs, case .user(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.chat, .chat): return {
        guard case .chat(let l) = lhs, case .chat(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension ChatMember: @unchecked Sendable {}
extension ChatSettings: @unchecked Sendable {}
extension SupportChatSettings: @unchecked Sendable {}
extension Chat: @unchecked Sendable {}
extension PeerUser: @unchecked Sendable {}
extension PeerChat: @unchecked Sendable {}
extension Peer: @unchecked Sendable {}
extension Peer.OneOf_OfPeer: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension ChatMember: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ChatMember"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "is_caller"),
    3: .same(proto: "type"),
    4: .standard(proto: "is_admin"),
    5: .standard(proto: "is_owner"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isCaller) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isAdmin) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.isOwner) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if self.isCaller != false {
      try visitor.visitSingularBoolField(value: self.isCaller, fieldNumber: 2)
    }
    if self.type != .userTypeUnknown {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 3)
    }
    if self.isAdmin != false {
      try visitor.visitSingularBoolField(value: self.isAdmin, fieldNumber: 4)
    }
    if self.isOwner != false {
      try visitor.visitSingularBoolField(value: self.isOwner, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ChatMember, rhs: ChatMember) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.isCaller != rhs.isCaller {return false}
    if lhs.type != rhs.type {return false}
    if lhs.isAdmin != rhs.isAdmin {return false}
    if lhs.isOwner != rhs.isOwner {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ChatSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ChatSettings"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "addContact"),
    2: .same(proto: "callAllowed"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.addContact) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.callAllowed) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.addContact != false {
      try visitor.visitSingularBoolField(value: self.addContact, fieldNumber: 1)
    }
    if self.callAllowed != false {
      try visitor.visitSingularBoolField(value: self.callAllowed, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ChatSettings, rhs: ChatSettings) -> Bool {
    if lhs.addContact != rhs.addContact {return false}
    if lhs.callAllowed != rhs.callAllowed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SupportChatSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SupportChatSettings"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "status"),
    2: .standard(proto: "assigned_support_manager"),
    3: .standard(proto: "postponed_time"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.assignedSupportManager) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.postponedTime) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.status != .supportChatStatusClosed {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    if !self.assignedSupportManager.isEmpty {
      try visitor.visitSingularStringField(value: self.assignedSupportManager, fieldNumber: 2)
    }
    if self.postponedTime != 0 {
      try visitor.visitSingularInt64Field(value: self.postponedTime, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SupportChatSettings, rhs: SupportChatSettings) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.assignedSupportManager != rhs.assignedSupportManager {return false}
    if lhs.postponedTime != rhs.postponedTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Chat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Chat"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_type"),
    2: .standard(proto: "chat_id"),
    3: .same(proto: "title"),
    4: .same(proto: "unread"),
    5: .same(proto: "members"),
    6: .same(proto: "messageSeqNumber"),
    7: .same(proto: "settings"),
    8: .same(proto: "supportSettings"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.chatType) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.chatID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.unread) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.members) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.messageSeqNumber) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._settings) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._supportSettings) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.chatType != .peerToPeer {
      try visitor.visitSingularEnumField(value: self.chatType, fieldNumber: 1)
    }
    if !self.chatID.isEmpty {
      try visitor.visitSingularStringField(value: self.chatID, fieldNumber: 2)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 3)
    }
    if self.unread != 0 {
      try visitor.visitSingularInt64Field(value: self.unread, fieldNumber: 4)
    }
    if !self.members.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.members, fieldNumber: 5)
    }
    if self.messageSeqNumber != 0 {
      try visitor.visitSingularUInt64Field(value: self.messageSeqNumber, fieldNumber: 6)
    }
    try { if let v = self._settings {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._supportSettings {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Chat, rhs: Chat) -> Bool {
    if lhs.chatType != rhs.chatType {return false}
    if lhs.chatID != rhs.chatID {return false}
    if lhs.title != rhs.title {return false}
    if lhs.unread != rhs.unread {return false}
    if lhs.members != rhs.members {return false}
    if lhs.messageSeqNumber != rhs.messageSeqNumber {return false}
    if lhs._settings != rhs._settings {return false}
    if lhs._supportSettings != rhs._supportSettings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PeerUser: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PeerUser"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "user_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.userID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PeerUser, rhs: PeerUser) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PeerChat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PeerChat"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.chatID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chatID.isEmpty {
      try visitor.visitSingularStringField(value: self.chatID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PeerChat, rhs: PeerChat) -> Bool {
    if lhs.chatID != rhs.chatID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Peer"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
    2: .same(proto: "chat"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: PeerUser?
        var hadOneofValue = false
        if let current = self.ofPeer {
          hadOneofValue = true
          if case .user(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.ofPeer = .user(v)
        }
      }()
      case 2: try {
        var v: PeerChat?
        var hadOneofValue = false
        if let current = self.ofPeer {
          hadOneofValue = true
          if case .chat(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.ofPeer = .chat(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.ofPeer {
    case .user?: try {
      guard case .user(let v)? = self.ofPeer else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .chat?: try {
      guard case .chat(let v)? = self.ofPeer else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Peer, rhs: Peer) -> Bool {
    if lhs.ofPeer != rhs.ofPeer {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
