//
//  SignUpWireframe.swift
//  Pods
//
//  Created by Slam on 4/14/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SignUpWireframe: BaseWireframe<SignUpViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -
    @discardableResult
    init(presentation controller: UIViewController) {
        let moduleViewController = SignUpViewController()
        super.init(viewController: moduleViewController)

        let interactor = SignUpInteractor()
        let presenter = SignUpPresenter(view: moduleViewController, wireframe: self)
        moduleViewController.presenter = presenter
        moduleViewController.modalPresentationStyle = .fullScreen
        controller.present(moduleViewController, animated: true)
    }
}

// MARK: - Extensions -

extension SignUpWireframe: SignUpWireframeInterface {
}
