# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Distribute a build to firebase app distribution"
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
    build_app
    firebase_app_distribution(
    	app: "1:1097507807917:ios:11ea4def5e4d65fc21dc24", 
    	firebase_cli_token: ENV['FB_TOKEN'],
    	groups: "ultra-testers"
    )
  end
end
