//
//  ContactsBookPresenter.swift
//  Pods
//
//  Created by Slam on 4/21/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//
import RxSwift
import Foundation

final class ContactsBookPresenter {
    
    // MARK: - Public properties -

    var contacts: BehaviorSubject<[ContactDisplayable]> = .init(value: [])

    // MARK: - Private properties -

    fileprivate let disposeBag = DisposeBag()
    private unowned let view: ContactsBookViewInterface
    private let wireframe: ContactsBookWireframeInterface
    fileprivate let bookContacts: UseCase<Void, ContactsBookInteractor.Contacts>
    fileprivate let syncContact: UseCase<ContactRequest, ContactResponse>
    // MARK: - Lifecycle -

    init(view: ContactsBookViewInterface,
         wireframe: ContactsBookWireframeInterface,
         syncContact: UseCase<ContactRequest, ContactResponse>,
         bookContacts: UseCase<Void, ContactsBookInteractor.Contacts>) {
        self.view = view
        self.wireframe = wireframe
        self.syncContact = syncContact
        self.bookContacts = bookContacts
    }
}

// MARK: - Extensions -

extension ContactsBookPresenter: ContactsBookPresenterInterface {
     
    func initial() {
        self.bookContacts
            .executeSingle(params: ())
            .flatMap({ result -> Single<ContactResponse> in
                var request = ContactRequest()
                request.contacts = result.contacts
                return self.syncContact.executeSingle(params: request)
            })
            .subscribe(on: ConcurrentDispatchQueueScheduler(qos: .background))
            .observe(on: MainScheduler.instance)
            .subscribe(onSuccess: { result in
                print(result)
            })
            .disposed(by: self.disposeBag)
    }
}
