//
//  ContactsBookInterfaces.swift
//  Pods
//
//  Created by Slam on 4/21/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

protocol ContactDisplayable: Any {
    var displaName: String { get set }
}

protocol ContactsBookWireframeInterface: WireframeInterface {
}

protocol ContactsBookViewInterface: ViewInterface {
}


protocol ContactsBookPresenterInterface: PresenterInterface {
    
    func initial()
    var contacts: BehaviorSubject<[ContactDisplayable]> { get set }
}
