// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_service.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(PhotoSize);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FileServiceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface FileServiceRoot : GPBRootObject
@end

#pragma mark - FileCreateRequest

typedef GPB_ENUM(FileCreateRequest_FieldNumber) {
  FileCreateRequest_FieldNumber_Name = 1,
  FileCreateRequest_FieldNumber_Size = 2,
  FileCreateRequest_FieldNumber_MimeType = 3,
};

GPB_FINAL @interface FileCreateRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int64_t size;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mimeType;

@end

#pragma mark - FileDownloadRequest

typedef GPB_ENUM(FileDownloadRequest_FieldNumber) {
  FileDownloadRequest_FieldNumber_FileId = 1,
  FileDownloadRequest_FieldNumber_FromChunkNumber = 2,
  FileDownloadRequest_FieldNumber_ToChunkNumber = 3,
};

GPB_FINAL @interface FileDownloadRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@property(nonatomic, readwrite) int64_t fromChunkNumber;

@property(nonatomic, readwrite) int64_t toChunkNumber;

@end

#pragma mark - FileCreateResponse

typedef GPB_ENUM(FileCreateResponse_FieldNumber) {
  FileCreateResponse_FieldNumber_FileId = 1,
  FileCreateResponse_FieldNumber_ChunkSize = 2,
};

GPB_FINAL @interface FileCreateResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@property(nonatomic, readwrite) int64_t chunkSize;

@end

#pragma mark - FileUploadAcceptedChunks

typedef GPB_ENUM(FileUploadAcceptedChunks_FieldNumber) {
  FileUploadAcceptedChunks_FieldNumber_FileId = 1,
  FileUploadAcceptedChunks_FieldNumber_AcceptedChunksArray = 2,
};

GPB_FINAL @interface FileUploadAcceptedChunks : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *acceptedChunksArray;
/** The number of items in @c acceptedChunksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger acceptedChunksArray_Count;

@end

#pragma mark - FileUploadResponse

GPB_FINAL @interface FileUploadResponse : GPBMessage

@end

#pragma mark - FileChunk

typedef GPB_ENUM(FileChunk_FieldNumber) {
  FileChunk_FieldNumber_FileId = 1,
  FileChunk_FieldNumber_Data_p = 2,
  FileChunk_FieldNumber_SeqNum = 3,
};

GPB_FINAL @interface FileChunk : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@property(nonatomic, readwrite) int64_t seqNum;

@end

#pragma mark - GetUploadedChunksRequest

typedef GPB_ENUM(GetUploadedChunksRequest_FieldNumber) {
  GetUploadedChunksRequest_FieldNumber_FileId = 1,
};

GPB_FINAL @interface GetUploadedChunksRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@end

#pragma mark - GetUploadedChunksResponse

typedef GPB_ENUM(GetUploadedChunksResponse_FieldNumber) {
  GetUploadedChunksResponse_FieldNumber_ChunksArray = 1,
};

GPB_FINAL @interface GetUploadedChunksResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *chunksArray;
/** The number of items in @c chunksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger chunksArray_Count;

@end

#pragma mark - PhotoDownloadRequest

typedef GPB_ENUM(PhotoDownloadRequest_FieldNumber) {
  PhotoDownloadRequest_FieldNumber_FileId = 1,
  PhotoDownloadRequest_FieldNumber_Size = 2,
};

GPB_FINAL @interface PhotoDownloadRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@property(nonatomic, readwrite) enum PhotoSize size;

@end

/**
 * Fetches the raw value of a @c PhotoDownloadRequest's @c size property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PhotoDownloadRequest_Size_RawValue(PhotoDownloadRequest *message);
/**
 * Sets the raw value of an @c PhotoDownloadRequest's @c size property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPhotoDownloadRequest_Size_RawValue(PhotoDownloadRequest *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
