// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_service.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Chat;
@class Message;
@class MessageMeta;
@class MessagesRange;
@class Peer;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageServiceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MessageServiceRoot : GPBRootObject
@end

#pragma mark - MessageSendRequest

typedef GPB_ENUM(MessageSendRequest_FieldNumber) {
  MessageSendRequest_FieldNumber_Peer = 1,
  MessageSendRequest_FieldNumber_Message = 2,
};

/**
 * *
 * Message send request
 **/
GPB_FINAL @interface MessageSendRequest : GPBMessage

/** target peer: person or chat */
@property(nonatomic, readwrite, strong, null_resettable) Peer *peer;
/** Test to see if @c peer has been set. */
@property(nonatomic, readwrite) BOOL hasPeer;

@property(nonatomic, readwrite, strong, null_resettable) Message *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - MessageSendResponse

typedef GPB_ENUM(MessageSendResponse_FieldNumber) {
  MessageSendResponse_FieldNumber_MessageId = 1,
  MessageSendResponse_FieldNumber_State = 2,
  MessageSendResponse_FieldNumber_Chat = 3,
  MessageSendResponse_FieldNumber_Meta = 4,
  MessageSendResponse_FieldNumber_SeqNumber = 5,
};

GPB_FINAL @interface MessageSendResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@property(nonatomic, readwrite) uint64_t state;

@property(nonatomic, readwrite, strong, null_resettable) Chat *chat;
/** Test to see if @c chat has been set. */
@property(nonatomic, readwrite) BOOL hasChat;

@property(nonatomic, readwrite, strong, null_resettable) MessageMeta *meta;
/** Test to see if @c meta has been set. */
@property(nonatomic, readwrite) BOOL hasMeta;

@property(nonatomic, readwrite) uint64_t seqNumber;

@end

#pragma mark - GetChatMessagesRequest

typedef GPB_ENUM(GetChatMessagesRequest_FieldNumber) {
  GetChatMessagesRequest_FieldNumber_ChatId = 1,
  GetChatMessagesRequest_FieldNumber_MaxSeqNumber = 2,
  GetChatMessagesRequest_FieldNumber_Limit = 3,
};

/**
 * Request to fetch chat messages in backward direction.
 **/
GPB_FINAL @interface GetChatMessagesRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

/** Maximum sequence number of message */
@property(nonatomic, readwrite) uint64_t maxSeqNumber;

/**
 * Message count limit. Maximum - 1000, any
 * higher number will be cut to 1000
 **/
@property(nonatomic, readwrite) int64_t limit;

@end

#pragma mark - GetChatMessagesResponse

typedef GPB_ENUM(GetChatMessagesResponse_FieldNumber) {
  GetChatMessagesResponse_FieldNumber_MessagesArray = 1,
};

GPB_FINAL @interface GetChatMessagesResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

@end

#pragma mark - MessagesDeliveredRequest

typedef GPB_ENUM(MessagesDeliveredRequest_FieldNumber) {
  MessagesDeliveredRequest_FieldNumber_ChatId = 1,
  MessagesDeliveredRequest_FieldNumber_MaxSeqNumber = 2,
};

GPB_FINAL @interface MessagesDeliveredRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@property(nonatomic, readwrite) uint64_t maxSeqNumber;

@end

#pragma mark - MessagesDeliveredResponse

typedef GPB_ENUM(MessagesDeliveredResponse_FieldNumber) {
  MessagesDeliveredResponse_FieldNumber_State = 1,
};

GPB_FINAL @interface MessagesDeliveredResponse : GPBMessage

@property(nonatomic, readwrite) uint64_t state;

@end

#pragma mark - MessagesReadRequest

typedef GPB_ENUM(MessagesReadRequest_FieldNumber) {
  MessagesReadRequest_FieldNumber_ChatId = 1,
  MessagesReadRequest_FieldNumber_MaxSeqNumber = 2,
};

GPB_FINAL @interface MessagesReadRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@property(nonatomic, readwrite) uint64_t maxSeqNumber;

@end

#pragma mark - MessagesReadResponse

typedef GPB_ENUM(MessagesReadResponse_FieldNumber) {
  MessagesReadResponse_FieldNumber_State = 1,
};

GPB_FINAL @interface MessagesReadResponse : GPBMessage

@property(nonatomic, readwrite) uint64_t state;

@end

#pragma mark - MessagesDeleteRequest

typedef GPB_ENUM(MessagesDeleteRequest_FieldNumber) {
  MessagesDeleteRequest_FieldNumber_ChatId = 1,
  MessagesDeleteRequest_FieldNumber_RangeArray = 2,
  MessagesDeleteRequest_FieldNumber_ForEveryone = 3,
};

GPB_FINAL @interface MessagesDeleteRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MessagesRange*> *rangeArray;
/** The number of items in @c rangeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rangeArray_Count;

@property(nonatomic, readwrite) BOOL forEveryone;

@end

#pragma mark - MessagesDeleteResponse

GPB_FINAL @interface MessagesDeleteResponse : GPBMessage

@end

#pragma mark - SendTypingRequest

typedef GPB_ENUM(SendTypingRequest_FieldNumber) {
  SendTypingRequest_FieldNumber_ChatId = 1,
};

GPB_FINAL @interface SendTypingRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@end

#pragma mark - SendTypingResponse

GPB_FINAL @interface SendTypingResponse : GPBMessage

@end

#pragma mark - SendAudioRecordingRequest

typedef GPB_ENUM(SendAudioRecordingRequest_FieldNumber) {
  SendAudioRecordingRequest_FieldNumber_ChatId = 1,
};

GPB_FINAL @interface SendAudioRecordingRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@end

#pragma mark - SendAudioRecordingResponse

GPB_FINAL @interface SendAudioRecordingResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
