// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: updates_service.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Chat;
@class Contact;
@class Message;
@class User;
@class UserState;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UpdatesServiceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface UpdatesServiceRoot : GPBRootObject
@end

#pragma mark - ListenRequest

typedef GPB_ENUM(ListenRequest_FieldNumber) {
  ListenRequest_FieldNumber_LocalState = 1,
};

GPB_FINAL @interface ListenRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserState *localState;
/** Test to see if @c localState has been set. */
@property(nonatomic, readwrite) BOOL hasLocalState;

@end

#pragma mark - InitialStateRequest

GPB_FINAL @interface InitialStateRequest : GPBMessage

@end

#pragma mark - InitialStateResponse

typedef GPB_ENUM(InitialStateResponse_FieldNumber) {
  InitialStateResponse_FieldNumber_State = 1,
  InitialStateResponse_FieldNumber_ChatsArray = 2,
  InitialStateResponse_FieldNumber_MessagesArray = 3,
  InitialStateResponse_FieldNumber_UsersArray = 4,
  InitialStateResponse_FieldNumber_ContactsArray = 5,
};

GPB_FINAL @interface InitialStateResponse : GPBMessage

@property(nonatomic, readwrite) uint64_t state;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Chat*> *chatsArray;
/** The number of items in @c chatsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger chatsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<User*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Contact*> *contactsArray;
/** The number of items in @c contactsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contactsArray_Count;

@end

#pragma mark - PingRequest

GPB_FINAL @interface PingRequest : GPBMessage

@end

#pragma mark - PingResponse

GPB_FINAL @interface PingResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
