// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class User;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserServiceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface UserServiceRoot : GPBRootObject
@end

#pragma mark - GetMeRequest

GPB_FINAL @interface GetMeRequest : GPBMessage

@end

#pragma mark - GetUserRequest

typedef GPB_ENUM(GetUserRequest_FieldNumber) {
  GetUserRequest_FieldNumber_UserId = 1,
  GetUserRequest_FieldNumber_Phone = 2,
};

/**
 * user_id or phone must be provided
 **/
GPB_FINAL @interface GetUserRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

@end

#pragma mark - GetUserResponse

typedef GPB_ENUM(GetUserResponse_FieldNumber) {
  GetUserResponse_FieldNumber_User = 1,
};

GPB_FINAL @interface GetUserResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) User *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@end

#pragma mark - UploadProfilePhotoRequest

typedef GPB_ENUM(UploadProfilePhotoRequest_FieldNumber) {
  UploadProfilePhotoRequest_FieldNumber_FileId = 1,
};

GPB_FINAL @interface UploadProfilePhotoRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@end

#pragma mark - UploadProfilePhotoResponse

typedef GPB_ENUM(UploadProfilePhotoResponse_FieldNumber) {
  UploadProfilePhotoResponse_FieldNumber_FileId = 1,
};

GPB_FINAL @interface UploadProfilePhotoResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
