//
//  ConversationsViewController.swift
//  Pods
//
//  Created by Slam on 4/20/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ConversationsViewController: BaseViewController<ConversationsPresenter> {

    // MARK: - Public properties -

    fileprivate lazy var tableView: UITableView = .init { [weak self] view in
        view.dataSource = self
    }
    // MARK: - Lifecycle -

}

// MARK: - Extensions -

extension ConversationsViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return .max
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return .init()
    }
    
    
}

extension ConversationsViewController: ConversationsViewInterface {
}
