//
//  ConversationsViewController.swift
//  Pods
//
//  Created by Slam on 4/20/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa
import RxDataSources

final class ConversationsViewController: BaseViewController<ConversationsPresenterInterface> {

    fileprivate lazy var permissionData = PermissionStateViewData(imageName: "conversations_empty",
                                                                  headline: ConversationsStrings.emptyMessages.localized,
                                                                  subline: ConversationsStrings.startCommunicatingWithYourContactsNow.localized.localized,
                                                                  action: .init(title: ConversationsStrings.start.localized, callback: {[weak self] in self?.presenter?.navigateToContacts()}))
    fileprivate lazy var backgroundView: PermissionStateView = .init(data: permissionData)
    
    fileprivate lazy var tableView = UITableView(frame: .zero, style: .plain)
    
    lazy var dataSource = RxTableViewSectionedReloadDataSource<SectionModel<String, Conversation>>(configureCell: {_, tableView, indexPath,
        model in
        
        let cell: ConversationCell = tableView.dequeueCell()
        cell.setup(
            conversation: model,
            isManager: self.presenter?.isManager(conversation: model) ?? false
        )
        return cell
    }, canEditRowAtIndexPath: { [weak self] data, indexpath in
        if self?.presenter?.isSupportScreen == true {
            return false
        } else if self?.presenter?.isManager(conversation: data.sectionModels[indexpath.section].items[indexpath.row]) == true {
            return false
        } else if let phone = data.sectionModels[indexpath.section].items[indexpath.row].peers.first?.phone {
            return !phone.contains("+00000000000")
        } else {
            return true
        }
    })
    override func setupViews() {
        super.setupViews()
        
        self.view.addSubview(tableView)
        self.tableView.rowHeight = 78
        self.tableView.backgroundColor = nil
        self.tableView.sectionHeaderHeight = 0
        self.tableView.registerCell(type: ConversationCell.self)
        self.navigationItem.rightBarButtonItem = .init(
            image: UltraCoreStyle.conversationScreenConfig.startConversationImage.image,
            style: .plain, target: self,
            action: #selector(self.openContacts)
        )
        self.tableView.contentInset = UIEdgeInsets(top: 24, left: 0, bottom: 0, right: 0)
        self.tableView.separatorInset = UIEdgeInsets(top: 0, left: 92, bottom: 0, right: 0)
        self.tableView.tableHeaderView = UIView()    
        self.navigationItem.title = ConversationsStrings.chats.localized
        self.hidesBottomBarWhenPushed = false
    }
    
    override func setupConstraints() {
        super.setupConstraints()
        self.tableView.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }
    }
    
    override func setupInitialData() {
        
        self.presenter?.conversation
            .subscribe(on: MainScheduler.instance)
            .observe(on: MainScheduler.instance)
            .debounce(.milliseconds(200), scheduler: MainScheduler.instance)
            .do(onNext: {[weak self] conversations in
                guard let `self` = self else { return }
                if conversations.isEmpty {
                    self.tableView.backgroundView = UltraCoreSettings.delegate?.emptyConversationView(isSupport: self.presenter?.isSupportScreen ?? false) ?? self.backgroundView
                } else {
                    self.tableView.backgroundView = nil
                }
            }).map({ conversation -> [SectionModel<String, Conversation>] in
                return [SectionModel<String, Conversation>.init(model: "", items: conversation)]
            })
                .bind(to: tableView.rx.items(dataSource: dataSource))
            .disposed(by: self.disposeBag)
        
        self.tableView
            .rx.itemSelected
            .subscribe { [weak self] (index: IndexPath) in
                guard let `self` = self else { return }
                self.tableView.deselectRow(at: index, animated: true)
            }
            .disposed(by: disposeBag)
        
        self.tableView
            .rx
            .modelDeleted(Conversation.self)
            .subscribe(onNext: {[weak self] conversation in
                guard let `self` = self else { return }
                let alert = UIAlertController.init(title: ConversationsStrings.areYouSure.localized, message: ConversationsStrings.pleaseNoteThatMessageDataWillBePermanentlyDeletedAndRecoveryWillNotBePossible.localized, preferredStyle: .actionSheet)
                alert.addAction(.init(title: ConversationsStrings.deleteFromMe.localized, style: .destructive, handler: { _ in
                    self.presenter?.delete(conversation, all: false)
                }))
                alert.addAction(.init(title: EditActionStrings.cancel.localized.capitalized, style: .cancel))
                self.present(alert, animated: true)
            })
            .disposed(by: disposeBag)
        
        self.tableView.rx
            .modelSelected(Conversation.self)
            .subscribe { [weak self](conversation: Conversation) in
                guard let `self` = self else { return }
                self.presenter?.navigate(to: conversation)
            }
            .disposed(by: disposeBag)
        
        presenter?.viewDidLoad()
    }
}

// MARK: - Extensions -

extension ConversationsViewController {
    @objc func openContacts(_ sender: Any) {
        self.presenter?.navigateToContacts()
    }
}

extension ConversationsViewController: ConversationsViewInterface {}
