//
//  ConversationsInterfaces.swift
//  Pods
//
//  Created by Slam on 4/20/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ConversationsWireframeInterface: WireframeInterface {
}

protocol ConversationsViewInterface: ViewInterface {
}

protocol ConversationsPresenterInterface: PresenterInterface {
}
