// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/update_types.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Contact;
@class Message;
@class MessagesDeleted;
@class MessagesDelivered;
@class MessagesRange;
@class MessagesRead;
@class Update;
@class UserAudioRecording;
@class UserStatus;
@class UserTyping;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UpdateTypesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface UpdateTypesRoot : GPBRootObject
@end

#pragma mark - MessagesDelivered

typedef GPB_ENUM(MessagesDelivered_FieldNumber) {
  MessagesDelivered_FieldNumber_ChatId = 1,
  MessagesDelivered_FieldNumber_UserId = 2,
  MessagesDelivered_FieldNumber_MaxSeqNumber = 3,
};

GPB_FINAL @interface MessagesDelivered : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) uint64_t maxSeqNumber;

@end

#pragma mark - MessagesRead

typedef GPB_ENUM(MessagesRead_FieldNumber) {
  MessagesRead_FieldNumber_ChatId = 1,
  MessagesRead_FieldNumber_UserId = 2,
  MessagesRead_FieldNumber_MaxSeqNumber = 3,
};

GPB_FINAL @interface MessagesRead : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) uint64_t maxSeqNumber;

@end

#pragma mark - MessagesDeleted

typedef GPB_ENUM(MessagesDeleted_FieldNumber) {
  MessagesDeleted_FieldNumber_ChatId = 1,
  MessagesDeleted_FieldNumber_RangeArray = 2,
};

GPB_FINAL @interface MessagesDeleted : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MessagesRange*> *rangeArray;
/** The number of items in @c rangeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rangeArray_Count;

@end

#pragma mark - UserTyping

typedef GPB_ENUM(UserTyping_FieldNumber) {
  UserTyping_FieldNumber_ChatId = 1,
  UserTyping_FieldNumber_UserId = 2,
};

GPB_FINAL @interface UserTyping : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - UserAudioRecording

typedef GPB_ENUM(UserAudioRecording_FieldNumber) {
  UserAudioRecording_FieldNumber_ChatId = 1,
  UserAudioRecording_FieldNumber_UserId = 2,
};

GPB_FINAL @interface UserAudioRecording : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - Update

typedef GPB_ENUM(Update_FieldNumber) {
  Update_FieldNumber_State = 1,
  Update_FieldNumber_Message = 3,
  Update_FieldNumber_Contact = 4,
  Update_FieldNumber_MessagesDelivered = 6,
  Update_FieldNumber_MessagesRead = 7,
  Update_FieldNumber_Typing = 8,
  Update_FieldNumber_AudioRecording = 9,
  Update_FieldNumber_UserStatus = 10,
  Update_FieldNumber_MessagesDeleted = 11,
};

typedef GPB_ENUM(Update_OfUpdate_OneOfCase) {
  Update_OfUpdate_OneOfCase_GPBUnsetOneOfCase = 0,
  Update_OfUpdate_OneOfCase_Message = 3,
  Update_OfUpdate_OneOfCase_Contact = 4,
  Update_OfUpdate_OneOfCase_MessagesDelivered = 6,
  Update_OfUpdate_OneOfCase_MessagesRead = 7,
  Update_OfUpdate_OneOfCase_MessagesDeleted = 11,
};

typedef GPB_ENUM(Update_OfPresence_OneOfCase) {
  Update_OfPresence_OneOfCase_GPBUnsetOneOfCase = 0,
  Update_OfPresence_OneOfCase_Typing = 8,
  Update_OfPresence_OneOfCase_AudioRecording = 9,
  Update_OfPresence_OneOfCase_UserStatus = 10,
};

GPB_FINAL @interface Update : GPBMessage

@property(nonatomic, readwrite) uint64_t state;

@property(nonatomic, readonly) Update_OfUpdate_OneOfCase ofUpdateOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) Message *message;

@property(nonatomic, readwrite, strong, null_resettable) Contact *contact;

@property(nonatomic, readwrite, strong, null_resettable) MessagesDelivered *messagesDelivered;

@property(nonatomic, readwrite, strong, null_resettable) MessagesRead *messagesRead;

@property(nonatomic, readwrite, strong, null_resettable) MessagesDeleted *messagesDeleted;

@property(nonatomic, readonly) Update_OfPresence_OneOfCase ofPresenceOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) UserTyping *typing;

@property(nonatomic, readwrite, strong, null_resettable) UserAudioRecording *audioRecording;

@property(nonatomic, readwrite, strong, null_resettable) UserStatus *userStatus;

@end

/**
 * Clears whatever value was set for the oneof 'ofUpdate'.
 **/
void Update_ClearOfUpdateOneOfCase(Update *message);
/**
 * Clears whatever value was set for the oneof 'ofPresence'.
 **/
void Update_ClearOfPresenceOneOfCase(Update *message);

#pragma mark - Updates

typedef GPB_ENUM(Updates_FieldNumber) {
  Updates_FieldNumber_LastState = 1,
  Updates_FieldNumber_Count = 2,
  Updates_FieldNumber_UpdatesArray = 4,
};

GPB_FINAL @interface Updates : GPBMessage

@property(nonatomic, readwrite) uint64_t lastState;

@property(nonatomic, readwrite) int64_t count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Update*> *updatesArray;
/** The number of items in @c updatesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger updatesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
